PACKAGE= com.isnetworks.crypto.database
CLASSES= SecureConnectionServer.class RemoteSQLException.class \
		 SecureDriver.class ConnectionProxy.class StatementProxy.class

#include the environment definitions
include $(CRYPTO_PROJECT_ROOT)/env/Makedefs
