PACKAGE= com.isnetworks.util.xml
CLASSES= DocumentHandlerAdapter.class XMLParsingException.class \
	XMLPropertyNode.class XPathSupport.class 
JOPTS=-g
#include the environment definitions
include $(CRYPTO_PROJECT_ROOT)/env/Makedefs
