PACKAGE= com.isnetworks.test.crypto.database
CLASSES= SecureDriverTestClient.class

#include the environment definitions
include $(CRYPTO_PROJECT_ROOT)/env/Makedefs

test: SecureDriverTestClient.class
	java com.isnetworks.test.crypto.database.SecureDriverTestClient
