PACKAGE= com.isnetworks.remote.proxy
CLASSES= OperationProxy.class OperationProxyImpl.class AbstractProxy.class \
		OperationProxyImpl_Stub.class
#include the environment definitions
include $(CRYPTO_PROJECT_ROOT)/env/Makedefs
