PACKAGE= com.isnetworks.test.remote.proxy
CLASSES= Test.class TestDelegate.class TestProxy.class TestServer.class \
		TestClient.class
#include the environment definitions
include $(CRYPTO_PROJECT_ROOT)/env/Makedefs
